export const components = {
  resource: "resource",
  workers: {
    soldier: "soldier",
    builder: "builder",
    servant: "servant",
    civilian: "civilian",
  },
  attributes: {
    renown: "renown",
    piety: "piety",
    valor: "valor",
    discipline: "discipline",
  },
  rewards: {
    production: "production",
    cohort: "cohort",
    trainingGroundSword: "trainingGroundSword",
    trader: "trader",
    performer: "performer",
    priest: "priest",
    apparitory: "apparitory",
    patrician: "patrician",
    scout: "scout",
  },
  buildings: {
    smallGranary: "smallGranary",
    mediumGranary: "mediumGranary",
    largeGranary: "largeGranary",
    smallHotel: "smallHotel",
    largeHotel: "largeHotel",
    smallWorkshop: "smallWorkshop",
    largeWorkshop: "largeWorkshop",
    smallRoad: "smallRoad",
    largeRoad: "largeRoad",
  },
  infrastructure: {
    one: "one",
    two: "two",
    three: "three",
    four: "four",
    five: "five",
    six: "six",
    seven: "seven",
    eight: "eight",
  },
};
export const config = {
  tracks: {
    cohort: {
      left: {
        inputs: [
          {
            id: 1,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 2,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 3,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
          {
            id: 4,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 5,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.valor],
          },
          {
            id: 6,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
        ],
      },
      center: {
        inputs: [
          {
            id: 1,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 2,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 3,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
          {
            id: 4,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 5,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.valor],
          },
          {
            id: 6,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
        ],
      },
      right: {
        inputs: [
          {
            id: 1,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 2,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 3,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
          {
            id: 4,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: null,
          },
          {
            id: 5,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.valor],
          },
          {
            id: 6,
            requiresPrevious: true,
            cost: [components.rewards.cohort],
            costOperator: "and",
            reward: [components.attributes.discipline],
          },
        ],
      },
    },
    miningAndForesting: {
      name: "Mining and Foresting",
      inputs: [
        {
          id: 1,
          column: "left",
          cost: [components.workers.servant],
          costOperator: "and",
          reward: null,
        },
        {
          id: 2,
          column: "left",
          requiresPrevious: true,
          cost: [components.workers.servant],
          costOperator: "and",
          reward: [components.rewards.production, components.resource],
        },
        {
          id: 3,
          column: "left",
          requiresPrevious: true,
          cost: [components.workers.servant],
          costOperator: "and",
          reward: null,
        },
        {
          id: 4,
          column: "left",
          requiresPrevious: true,
          cost: [components.workers.servant],
          costOperator: "and",
          reward: null,
        },

        {
          id: 5,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.servant,
            components.buildings.mediumGranary,
          ],
          costOperator: "and",
          reward: [components.rewards.production, components.resource],
        },
        {
          id: 6,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.servant,
            components.buildings.mediumGranary,
          ],
          costOperator: "and",
          reward: null,
        },
        {
          id: 7,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.servant,
            components.buildings.mediumGranary,
          ],
          costOperator: "and",
          reward: null,
        },
        {
          id: 8,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.servant,
            components.buildings.mediumGranary,
          ],
          costOperator: "and",
          reward: [components.rewards.production, components.resource],
        },
        {
          id: 9,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.servant,
            components.buildings.mediumGranary,
          ],
          costOperator: "and",
          reward: null,
        },
        {
          id: 10,
          column: "right",
          requiresPrevious: true,
          cost: [components.workers.servant, components.buildings.largeGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 11,
          column: "right",
          requiresPrevious: true,
          cost: [components.workers.servant, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.rewards.production, components.resource],
        },
        {
          id: 12,
          column: "right",
          requiresPrevious: true,
          cost: [components.workers.servant, components.buildings.largeGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 13,
          column: "right",
          requiresPrevious: true,
          cost: [components.workers.servant, components.buildings.largeGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 14,
          column: "right",
          requiresPrevious: true,
          cost: [components.workers.servant, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.rewards.production, components.resource],
        },
      ],
    },
    wallGuard: {
      name: "Wall Guard",
      inputs: [
        {
          id: 1,
          column: "left",
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 2,
          column: "left",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 3,
          column: "left",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 4,
          column: "left",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: null,
        },
        {
          id: 5,
          column: "left",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 6,
          column: "left",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 7,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: null,
        },
        {
          id: 8,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 9,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 10,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: null,
        },
        {
          id: 11,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 12,
          column: "center",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 13,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: null,
        },
        {
          id: 14,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 15,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
        {
          id: 16,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: null,
        },
        {
          id: 17,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.attributes.discipline],
        },
        {
          id: 18,
          column: "right",
          requiresPrevious: true,
          cost: [
            components.workers.soldier,
            components.rewards.trainingGroundSword,
          ],
          costOperator: "or",
          reward: [components.rewards.cohort],
        },
      ],
    },
    cippi: {
      name: "Cippi",
      inputs: [
        {
          id: 1,
          column: "left",
          cost: [components.resource],
          reward: null,
        },
        {
          id: 2,
          column: "left",
          requiresPrevious: true,
          cost: [components.resource],
          reward: null,
        },
        {
          id: 3,
          column: "left",
          requiresPrevious: true,
          cost: [components.resource],
          reward: [components.rewards.cohort],
        },
        {
          id: 4,
          column: "center",
          requiresPrevious: true,
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.workers.civilian],
        },
        {
          id: 5,
          column: "center",
          requiresPrevious: true,
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.rewards.cohort],
        },
        {
          id: 6,
          column: "right",
          requiresPrevious: true,
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.attributes.renown],
        },
        {
          id: 7,
          column: "right",
          requiresPrevious: true,
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.rewards.cohort],
        },
      ],
    },
    wall: {
      name: "Wall",
      inputs: [
        {
          id: 1,
          column: "left",
          cost: [components.resource],
          reward: [components.workers.civilian],
        },
        {
          id: 2,
          column: "left",
          cost: [components.resource],
          reward: null,
        },
        {
          id: 3,
          column: "left",
          cost: [components.resource],
          reward: [components.workers.civilian],
        },
        {
          id: 4,
          column: "left",
          cost: [components.resource],
          reward: [components.attributes.renown, components.rewards.cohort],
        },
        {
          id: 5,
          column: "left",
          cost: [components.resource],
          reward: [components.workers.civilian],
        },
        {
          id: 6,
          column: "left",
          cost: [components.resource],
          reward: null,
        },
        {
          id: 7,
          column: "left",
          cost: [components.resource],
          reward: [components.rewards.cohort],
        },
        {
          id: 8,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.attributes.renown],
        },
        {
          id: 9,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.workers.civilian],
        },
        {
          id: 10,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 11,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.attributes.renown, components.rewards.cohort],
        },
        {
          id: 12,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 13,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.workers.civilian],
        },
        {
          id: 14,
          column: "center",
          cost: [components.resource, components.buildings.mediumGranary],
          costOperator: "and",
          reward: [components.rewards.cohort],
        },
        {
          id: 15,
          column: "center",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.attributes.renown],
        },
        {
          id: 16,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.workers.civilian],
        },
        {
          id: 17,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 18,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.attributes.renown, components.rewards.cohort],
        },
        {
          id: 19,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.workers.civilian],
        },
        {
          id: 20,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: null,
        },
        {
          id: 21,
          column: "right",
          cost: [components.resource, components.buildings.largeGranary],
          costOperator: "and",
          reward: [components.rewards.cohort],
        },
      ],
    },
  },
};
